#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

git clone https://${GH_TOKEN}@github.com/VictorAlbertos/VictorAlbertos.github.io.git  --branch develop temp
cd temp

# push
mv ./.git ./_site
cd _site
git branch -m master

git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"

git remote add site https://${GH_TOKEN}@github.com/VictorAlbertos/VictorAlbertos.github.io.git
git push --force site master