#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

git clone https://${GH_TOKEN}@github.com/VictorAlbertos/staging-desobra.git  --branch sources temp
cd temp

# mv ./.git ./_site
# cd _site

gem install bundler
gem install jekyll
gem jekyll-paginate-v2

pip install pyyaml
python scripts/generate_jekyll_blueprint.py 
python scripts/prepare_gitignore_for_deployment.py

git branch -m master

git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"

git remote add site https://${GH_TOKEN}@github.com/VictorAlbertos/staging-desobra.git
git push --force site master