#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

git clone https://${GH_TOKEN}@github.com/VictorAlbertos/staging-desobra.git  --branch sources temp
cd temp